import type { ComponentType } from "react";
import { PowerExplorerGame, ProportionTestGame, SteelCutoffGame } from "../games";
import { CoverScene, OutlineScene, Part1Scene, Part2Scene, Part3Scene, Part4Scene } from "./courseScenes";
import {
  AlphaBetaScene,
  AlphaBetaSolutionScene,
  Case1FigureScene,
  Case1LowerScene,
  Case1StatScene,
  Case1TwoScene,
  Case1UpperScene,
  Case2LowerScene,
  Case2StatScene,
  Case2TwoScene,
  Case2UpperScene,
  CriticalRegionScene,
  DecisionRuleScene,
  ErrorTableScene,
  HypothesisTypesScene,
  HypothesesScene,
  L6IntroScene,
  MeanSetupScene,
  OneMeanSummaryScene,
  OneSidedDecisionScene,
  OneSidedSetupScene,
  PValueScene,
  RecallSteelScene,
  SignificanceScene,
  SteelExampleScene,
  ThreeApproachesScene,
  TumorDecisionScene,
  TumorSetupScene,
  TypeErrorPlotScene,
} from "./lecture6Scenes";
import {
  FCriticalScene,
  FDecisionScene,
  FPvalueScene,
  FStatScene,
  L7IntroScene,
  PairedDecisionScene,
  PairedExampleDecisionScene,
  PairedExampleSetupScene,
  PairedStatScene,
  PooledExampleScene,
  PooledLowerScene,
  PooledStatScene,
  PooledTwoScene,
  PooledUpperScene,
  RecapFrameworkScene,
  TwoMeansSetupScene,
  TwoSampleSummaryScene,
  VarianceSetupScene,
  WelchStatScene,
  WelchTwoScene,
} from "./lecture7Scenes";
import {
  BirthExampleScene,
  DiceDecisionScene,
  DiceSetupScene,
  L8IntroScene,
  PropCltScene,
  PropLowerScene,
  PropSetupScene,
  PropStatScene,
  PropSummaryScene,
  PropTwoScene,
  PropUpperScene,
  TwoPropDecisionScene,
  TwoPropNullScene,
  TwoPropSamplingScene,
  TwoPropSetupScene,
  TwoPropStatScene,
} from "./lecture8Scenes";
import {
  AlphaFixedPowerScene,
  AlphaFixedScene,
  At60Scene,
  At65Scene,
  BinomialAlphaScene,
  BinomialCheck1Scene,
  BinomialCheck2Scene,
  BinomialEq1Scene,
  BinomialEq2Scene,
  BinomialNSetupScene,
  BinomialPowerScene,
  BinomialSetupScene,
  CompositeNullScene,
  EmsSetupScene,
  EmsSolutionScene,
  L9IntroScene,
  LowerPowerScene,
  PowerAlphaBetaScene,
  PowerDefScene,
  PowerFactorsScene,
  PowerRecallScene,
  PowerSummaryScene,
  ProportionTakeawaysScene,
  SampleSizeFormulaScene,
  SampleSizeMotivationScene,
  SampleSizeSolveScene,
  TeachingCurveScene,
  TeachingSetupScene,
  TeachingSolutionScene,
  ToothpasteSetupScene,
  ToothpasteSolutionScene,
  TwoSampleNScene,
  TwoSamplePowerFnScene,
  TwoSamplePowerSetupScene,
  TwoSidedNFormulaScene,
  TwoSidedNSetupScene,
  TwoSidedPowerDeriveScene,
  TwoSidedPowerSetupScene,
  UpperPowerDeriveScene,
  UpperPowerPhiScene,
  WhyKnownSigmaScene,
} from "./lecture9Scenes";

export type SceneDef = {
  id: string;
  chapter: string;
  label: string;
  Scene: ComponentType;
};

export const SCENES: SceneDef[] = [
  { id: "cover", chapter: "Welcome", label: "Cover", Scene: CoverScene },
  { id: "outline", chapter: "Welcome", label: "Outline", Scene: OutlineScene },
  { id: "part1", chapter: "Part I", label: "Hypothesis Testing I", Scene: Part1Scene },
  { id: "l6-intro", chapter: "Part I", label: "Introduction", Scene: L6IntroScene },
  { id: "steel", chapter: "Part I", label: "Steel bars", Scene: SteelExampleScene },
  { id: "hypotheses", chapter: "Part I", label: "H0 and H1", Scene: HypothesesScene },
  { id: "hyp-types", chapter: "Part I", label: "Types of hypotheses", Scene: HypothesisTypesScene },
  { id: "critical", chapter: "Part I", label: "Critical region", Scene: CriticalRegionScene },
  { id: "decision", chapter: "Part I", label: "Decision rule", Scene: DecisionRuleScene },
  { id: "recall", chapter: "Part I", label: "Recall the example", Scene: RecallSteelScene },
  { id: "errors", chapter: "Part I", label: "Error table", Scene: ErrorTableScene },
  { id: "alpha-beta", chapter: "Part I", label: "α and β", Scene: AlphaBetaScene },
  { id: "alpha-beta-sol", chapter: "Part I", label: "Compute α and β", Scene: AlphaBetaSolutionScene },
  { id: "type-plot", chapter: "Part I", label: "Error regions", Scene: TypeErrorPlotScene },
  { id: "game-cutoff", chapter: "Game", label: "Cutoff explorer", Scene: SteelCutoffGame },
  { id: "alpha", chapter: "Part I", label: "Significance level", Scene: SignificanceScene },
  { id: "pvalue", chapter: "Part I", label: "p-value", Scene: PValueScene },
  { id: "mean-setup", chapter: "One mean", label: "Two cases", Scene: MeanSetupScene },
  { id: "three", chapter: "One mean", label: "Three approaches", Scene: ThreeApproachesScene },
  { id: "z-stat", chapter: "Case 1", label: "z statistic", Scene: Case1StatScene },
  { id: "z-upper", chapter: "Case 1", label: "μ > μ0", Scene: Case1UpperScene },
  { id: "z-lower", chapter: "Case 1", label: "μ < μ0", Scene: Case1LowerScene },
  { id: "z-two", chapter: "Case 1", label: "μ ≠ μ0", Scene: Case1TwoScene },
  { id: "z-fig", chapter: "Case 1", label: "Rejection regions", Scene: Case1FigureScene },
  { id: "t-stat", chapter: "Case 2", label: "t statistic", Scene: Case2StatScene },
  { id: "t-upper", chapter: "Case 2", label: "μ > μ0", Scene: Case2UpperScene },
  { id: "t-lower", chapter: "Case 2", label: "μ < μ0", Scene: Case2LowerScene },
  { id: "t-two", chapter: "Case 2", label: "μ ≠ μ0", Scene: Case2TwoScene },
  { id: "tumor", chapter: "Case 2", label: "Tumor growth", Scene: TumorSetupScene },
  { id: "tumor-dec", chapter: "Case 2", label: "Tumor decision", Scene: TumorDecisionScene },
  { id: "oneside", chapter: "Case 2", label: "One-sided example", Scene: OneSidedSetupScene },
  { id: "oneside-dec", chapter: "Case 2", label: "One-sided decision", Scene: OneSidedDecisionScene },
  { id: "sum-mean", chapter: "Part I", label: "Summary table", Scene: OneMeanSummaryScene },
  { id: "part2", chapter: "Part II", label: "Hypothesis Testing II", Scene: Part2Scene },
  { id: "l7-intro", chapter: "Part II", label: "Introduction", Scene: L7IntroScene },
  { id: "recap", chapter: "Part II", label: "Framework", Scene: RecapFrameworkScene },
  { id: "two-means", chapter: "Two means", label: "Three cases", Scene: TwoMeansSetupScene },
  { id: "pooled-stat", chapter: "Pooled t", label: "Statistic", Scene: PooledStatScene },
  { id: "pooled-up", chapter: "Pooled t", label: "μX > μY", Scene: PooledUpperScene },
  { id: "pooled-lo", chapter: "Pooled t", label: "μX < μY", Scene: PooledLowerScene },
  { id: "pooled-two", chapter: "Pooled t", label: "μX ≠ μY", Scene: PooledTwoScene },
  { id: "pooled-ex", chapter: "Pooled t", label: "Example", Scene: PooledExampleScene },
  { id: "welch-stat", chapter: "Welch t", label: "Statistic", Scene: WelchStatScene },
  { id: "welch-two", chapter: "Welch t", label: "Two-sided", Scene: WelchTwoScene },
  { id: "paired-stat", chapter: "Paired t", label: "Statistic", Scene: PairedStatScene },
  { id: "paired-dec", chapter: "Paired t", label: "Decision", Scene: PairedDecisionScene },
  { id: "paired-ex", chapter: "Paired t", label: "Rope jumping", Scene: PairedExampleSetupScene },
  { id: "paired-sol", chapter: "Paired t", label: "Rope decision", Scene: PairedExampleDecisionScene },
  { id: "var-setup", chapter: "F-test", label: "Two variances", Scene: VarianceSetupScene },
  { id: "f-stat", chapter: "F-test", label: "F statistic", Scene: FStatScene },
  { id: "f-crit", chapter: "F-test", label: "Critical region", Scene: FCriticalScene },
  { id: "f-p", chapter: "F-test", label: "p-value", Scene: FPvalueScene },
  { id: "f-dec", chapter: "F-test", label: "Decision rules", Scene: FDecisionScene },
  { id: "sum-two", chapter: "Part II", label: "Summary table", Scene: TwoSampleSummaryScene },
  { id: "part3", chapter: "Part III", label: "Hypothesis Testing III", Scene: Part3Scene },
  { id: "l8-intro", chapter: "Part III", label: "Introduction", Scene: L8IntroScene },
  { id: "prop-setup", chapter: "Proportions", label: "Bernoulli sample", Scene: PropSetupScene },
  { id: "prop-clt", chapter: "Proportions", label: "CLT", Scene: PropCltScene },
  { id: "prop-stat", chapter: "Proportions", label: "Test statistic", Scene: PropStatScene },
  { id: "prop-up", chapter: "Proportions", label: "p > p0", Scene: PropUpperScene },
  { id: "prop-lo", chapter: "Proportions", label: "p < p0", Scene: PropLowerScene },
  { id: "prop-two", chapter: "Proportions", label: "p ≠ p0", Scene: PropTwoScene },
  { id: "dice", chapter: "Proportions", label: "Dice example", Scene: DiceSetupScene },
  { id: "dice-sol", chapter: "Proportions", label: "Dice solution", Scene: DiceDecisionScene },
  { id: "game-prop", chapter: "Game", label: "Proportion z test", Scene: ProportionTestGame },
  { id: "twop-setup", chapter: "Two proportions", label: "Setup", Scene: TwoPropSetupScene },
  { id: "twop-samp", chapter: "Two proportions", label: "Sampling", Scene: TwoPropSamplingScene },
  { id: "twop-null", chapter: "Two proportions", label: "Under H0", Scene: TwoPropNullScene },
  { id: "twop-stat", chapter: "Two proportions", label: "Pooled p", Scene: TwoPropStatScene },
  { id: "twop-dec", chapter: "Two proportions", label: "Decision", Scene: TwoPropDecisionScene },
  { id: "birth", chapter: "Two proportions", label: "Birth weight", Scene: BirthExampleScene },
  { id: "sum-prop", chapter: "Part III", label: "Summary table", Scene: PropSummaryScene },
  { id: "part4", chapter: "Part IV", label: "Hypothesis Testing IV", Scene: Part4Scene },
  { id: "l9-intro", chapter: "Part IV", label: "Introduction", Scene: L9IntroScene },
  { id: "power-recall", chapter: "Power", label: "Type II error", Scene: PowerRecallScene },
  { id: "power-def", chapter: "Power", label: "K(μ)", Scene: PowerDefScene },
  { id: "power-link", chapter: "Power", label: "Link to α, β", Scene: PowerAlphaBetaScene },
  { id: "teach", chapter: "Power", label: "Teaching example", Scene: TeachingSetupScene },
  { id: "teach-sol", chapter: "Power", label: "K(μ) formula", Scene: TeachingSolutionScene },
  { id: "teach-curve", chapter: "Power", label: "Power curve", Scene: TeachingCurveScene },
  { id: "mu60", chapter: "Power", label: "At μ = 60", Scene: At60Scene },
  { id: "composite", chapter: "Power", label: "Composite null", Scene: CompositeNullScene },
  { id: "mu65", chapter: "Power", label: "At μ = 65", Scene: At65Scene },
  { id: "alpha05", chapter: "Power", label: "Fix α = 0.05", Scene: AlphaFixedScene },
  { id: "alpha05-k", chapter: "Power", label: "Power after fixing α", Scene: AlphaFixedPowerScene },
  { id: "k-derive", chapter: "Power", label: "Upper-tail derivation", Scene: UpperPowerDeriveScene },
  { id: "k-phi", chapter: "Power", label: "Closed form", Scene: UpperPowerPhiScene },
  { id: "factors", chapter: "Power", label: "What changes power", Scene: PowerFactorsScene },
  { id: "game-power", chapter: "Game", label: "Power explorer", Scene: PowerExplorerGame },
  { id: "k-lower", chapter: "Power", label: "Lower tail", Scene: LowerPowerScene },
  { id: "ems", chapter: "Power", label: "Emergency times", Scene: EmsSetupScene },
  { id: "ems-sol", chapter: "Power", label: "Emergency solution", Scene: EmsSolutionScene },
  { id: "k2-setup", chapter: "Power", label: "Two-sided setup", Scene: TwoSidedPowerSetupScene },
  { id: "k2-derive", chapter: "Power", label: "Two-sided formula", Scene: TwoSidedPowerDeriveScene },
  { id: "paste", chapter: "Power", label: "Toothpaste", Scene: ToothpasteSetupScene },
  { id: "paste-sol", chapter: "Power", label: "Toothpaste solution", Scene: ToothpasteSolutionScene },
  { id: "known-s", chapter: "Power", label: "Why known σ", Scene: WhyKnownSigmaScene },
  { id: "n-mot", chapter: "Sample size", label: "Both errors", Scene: SampleSizeMotivationScene },
  { id: "n-solve", chapter: "Sample size", label: "Solve c and n", Scene: SampleSizeSolveScene },
  { id: "n-formula", chapter: "Sample size", label: "One-sided formula", Scene: SampleSizeFormulaScene },
  { id: "n2-setup", chapter: "Sample size", label: "Two-sided setup", Scene: TwoSidedNSetupScene },
  { id: "n2-formula", chapter: "Sample size", label: "Two-sided formula", Scene: TwoSidedNFormulaScene },
  { id: "n-2s", chapter: "Sample size", label: "Two-sample setup", Scene: TwoSamplePowerSetupScene },
  { id: "k-2s", chapter: "Sample size", label: "Two-sample power", Scene: TwoSamplePowerFnScene },
  { id: "n-2s-formula", chapter: "Sample size", label: "Two-sample n", Scene: TwoSampleNScene },
  { id: "sum-power", chapter: "Part IV", label: "Summary table", Scene: PowerSummaryScene },
  { id: "bin-setup", chapter: "Proportions", label: "Binomial test", Scene: BinomialSetupScene },
  { id: "bin-k", chapter: "Proportions", label: "K(p)", Scene: BinomialPowerScene },
  { id: "bin-ab", chapter: "Proportions", label: "α and β", Scene: BinomialAlphaScene },
  { id: "bin-n", chapter: "Proportions", label: "Target errors", Scene: BinomialNSetupScene },
  { id: "bin-eq1", chapter: "Proportions", label: "Type I equation", Scene: BinomialEq1Scene },
  { id: "bin-eq2", chapter: "Proportions", label: "Type II equation", Scene: BinomialEq2Scene },
  { id: "bin-chk1", chapter: "Proportions", label: "Check n = 31, 32", Scene: BinomialCheck1Scene },
  { id: "bin-chk2", chapter: "Proportions", label: "Check n = 33", Scene: BinomialCheck2Scene },
  { id: "takeaways", chapter: "Part IV", label: "Takeaways", Scene: ProportionTakeawaysScene },
];
