import type { ComponentType } from "react";
import {
  CltCoverageGame,
  CoverageGame,
  PropCiGame,
  SampleSizeGame,
  TVsZGame,
  TwoSampleGame,
  ZIntervalGame,
} from "../games";
import {
  Case1DeriveScene,
  Case1ExampleScene,
  Case1PropsScene,
  Case2ExampleScene,
  Case2Scene,
  Case3ExampleScene,
  Case3FormulaScene,
  Case3IntroScene,
  Case4Scene,
  CiDefinitionScene,
  DesignActivityScene,
  DesignMapScene,
  DiffCompareScene,
  DiffMeansSetupScene,
  FourCasesScene,
  OneSidedFormulaScene,
  OneSidedScene,
  PairedDefScene,
  PairedExampleScene,
  PairedProofScene,
  PairedTheoremScene,
  Part1SummaryScene,
  Part2IntroScene,
  PooledExampleScene,
  PooledTheoremScene,
  PropDeriveScene,
  PropDiffExampleScene,
  PropDiffScene,
  PropExampleScene,
  PropSetupScene,
  SampleSizeAptScene,
  SampleSizeMeanExampleScene,
  SampleSizeMeanScene,
  SampleSizePropScene,
  TakeawaysScene,
  UnpairedOnPairedDataScene,
  WelchExampleScene,
  WelchTheoremScene,
} from "./contentScenes";
import { CoverScene, OutlineScene, ReadingScene } from "./courseScenes";

export type SceneDef = {
  id: string;
  chapter: string;
  label: string;
  Scene: ComponentType;
};

export const SCENES: SceneDef[] = [
  { id: "cover", chapter: "Welcome", label: "Cover", Scene: CoverScene },
  { id: "outline", chapter: "Welcome", label: "Outline", Scene: OutlineScene },
  { id: "reading", chapter: "Welcome", label: "What we learn", Scene: ReadingScene },
  { id: "ci-def", chapter: "Foundations", label: "CI definition", Scene: CiDefinitionScene },
  { id: "four-cases", chapter: "Mean", label: "Four cases", Scene: FourCasesScene },
  { id: "case1-derive", chapter: "Case 1", label: "Normal σ known", Scene: Case1DeriveScene },
  { id: "case1-props", chapter: "Case 1", label: "z-interval properties", Scene: Case1PropsScene },
  { id: "case1-ex", chapter: "Case 1", label: "Bulb example", Scene: Case1ExampleScene },
  { id: "game-z", chapter: "Game", label: "z-interval explorer", Scene: ZIntervalGame },
  { id: "game-cover", chapter: "Game", label: "Coverage simulator", Scene: CoverageGame },
  { id: "case2", chapter: "Case 2", label: "CLT, σ known", Scene: Case2Scene },
  { id: "case2-ex", chapter: "Case 2", label: "Juice example", Scene: Case2ExampleScene },
  { id: "game-clt-cover", chapter: "Game", label: "CLT coverage explorer", Scene: CltCoverageGame },
  { id: "case3-intro", chapter: "Case 3", label: "σ unknown", Scene: Case3IntroScene },
  { id: "case3-formula", chapter: "Case 3", label: "t-interval", Scene: Case3FormulaScene },
  { id: "case3-ex", chapter: "Case 3", label: "Entrance exam", Scene: Case3ExampleScene },
  { id: "game-tvz", chapter: "Game", label: "z vs t", Scene: TVsZGame },
  { id: "case4", chapter: "Case 4", label: "Approx. t / z", Scene: Case4Scene },
  { id: "onesided", chapter: "One-sided", label: "Motivation", Scene: OneSidedScene },
  { id: "onesided-f", chapter: "One-sided", label: "Bounds", Scene: OneSidedFormulaScene },
  { id: "part1-sum", chapter: "Summary", label: "CI for μ table", Scene: Part1SummaryScene },
  { id: "part2", chapter: "Part II", label: "Beyond one mean", Scene: Part2IntroScene },
  { id: "diff-setup", chapter: "Two means", label: "Three designs", Scene: DiffMeansSetupScene },
  { id: "pooled", chapter: "Pooled t", label: "Equal σ²", Scene: PooledTheoremScene },
  { id: "pooled-ex", chapter: "Pooled t", label: "Schools example", Scene: PooledExampleScene },
  { id: "welch", chapter: "Welch t", label: "Unequal σ²", Scene: WelchTheoremScene },
  { id: "welch-ex", chapter: "Welch t", label: "Welch example", Scene: WelchExampleScene },
  { id: "paired-def", chapter: "Paired t", label: "Paired samples", Scene: PairedDefScene },
  { id: "design", chapter: "Design", label: "Hair styles", Scene: DesignActivityScene },
  { id: "paired", chapter: "Paired t", label: "Paired CI", Scene: PairedTheoremScene },
  { id: "paired-proof", chapter: "Paired t", label: "Why t", Scene: PairedProofScene },
  { id: "paired-ex", chapter: "Paired t", label: "Reaction times", Scene: PairedExampleScene },
  { id: "unpaired-cmp", chapter: "Paired t", label: "Unpaired on same data", Scene: UnpairedOnPairedDataScene },
  { id: "game-2s", chapter: "Game", label: "Pooled / Welch / paired", Scene: TwoSampleGame },
  { id: "diff-cmp", chapter: "Two means", label: "Width comparison", Scene: DiffCompareScene },
  { id: "design-map", chapter: "Design", label: "Which CI?", Scene: DesignMapScene },
  { id: "prop-setup", chapter: "Proportions", label: "Bernoulli setup", Scene: PropSetupScene },
  { id: "prop-derive", chapter: "Proportions", label: "CLT → CI", Scene: PropDeriveScene },
  { id: "prop-ex", chapter: "Proportions", label: "Campaign example", Scene: PropExampleScene },
  { id: "game-prop", chapter: "Game", label: "Prop. vs sample var", Scene: PropCiGame },
  { id: "prop-diff", chapter: "Proportions", label: "p1 − p2", Scene: PropDiffScene },
  { id: "prop-diff-ex", chapter: "Proportions", label: "Gaming example", Scene: PropDiffExampleScene },
  { id: "n-mean", chapter: "Sample size", label: "Margin for μ", Scene: SampleSizeMeanScene },
  { id: "n-mean-ex", chapter: "Sample size", label: "Memory test", Scene: SampleSizeMeanExampleScene },
  { id: "game-n", chapter: "Game", label: "Sample size planner", Scene: SampleSizeGame },
  { id: "n-prop", chapter: "Sample size", label: "n for a proportion", Scene: SampleSizePropScene },
  { id: "n-apt", chapter: "Sample size", label: "Apartments", Scene: SampleSizeAptScene },
  { id: "takeaways", chapter: "Summary", label: "Takeaways", Scene: TakeawaysScene },
];
